%
%	File STATIC_U.M
%
%	Function: STATIC_U
%
%	Call: [u1s,u2s,y1sr,y2sr] = static_u(static_map,y1s,y2s) ;
%
%	Returns the static inputs of intallation ASTANK2, by using the admissible static map. 
%	Performs linear interpolation to compute the results.  
%
%	The admissible static map can be generated by means of 
%	STATIC_ADMISSIBLE_COMMANDS_ASTANK2 function, depending on the static 
%	maps of ASTANK2 installation. 
%
%	Input arguments:
%	  . static_map = structure structure with the fields:
%	                  . U1 = static control input on channel 1 (column vector);
%	                  . U2 = static control input on channel 1 (column vector);
%	                  . Y1 = static level on tank 1 (matrix);
%	                  . Y1 = static level on tank 2 (matrix).
%	  . y1s = output static value for tank 1 (scalar);
%	  . y2s = output static value for tank 2 (scalar).
%
%	Output arguments:
%	  . u1s = static command on channel 1 (scalar);
%	  . u2s = static command on channel 2 (scalar);
%	  . y1sr = corrected output static value for tank 2.
%	  . y2sr = corrected output static value for tank 2.
%
%	Missing or void arguments return empty outputs .  
%
%	Uses:	 STATIC_ADMISSIBLE_COMMANDS_ASTANK2
%	         WAR_ERR 
%
%	Author:	 Dan STEFANOIU
%	Created: April 24, 2025
%	Revised: April 25, 2025
%

function [u1s,u2s,y1sr,y2sr] = static_u(static_map,y1s,y2s)

%
% BEGIN
%
% Constants & Messages 
% ~~~~~~~~~~~~~~~~~~~~
	FN = '<STATIC_U>: ' ;
	E = [FN 'Missing, empty or inconsistent inputs => empty outputs. Exit.'] ; 
%
% Partial faults preventing (structure of admissible static map not tested)
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	[u1s,u2s] = deal([]) ; 
	if (nargin<3)
	   war_err(E) ;
	   return ;
	end ; 
	E = [FN 'Inadmissible couple of static output values. Empty outputs. Exit.'] ;
	y1s = y1s(1) ;
	y2s = y2s(1) ;
%
% Generating the admissible static map
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	YUa = Static_admissible_commands_ASTANK2(static_map) ;
%
% Computing the static commands
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	FN = 1:size(YUa,2) ;
	m = (YUa(1,:)<=y1s) & (YUa(2,:)<=y2s) ;
	n = FN(m) ;
	n = n(end) ;
	m = (YUa(1,:)>y1s) & (YUa(2,:)>y2s) ;
	m = FN(m) ;
	m = m(1) ;
	FN = min(m,n) ;
	n = max(m,n) ;
	m = FN ; 
	[~,FN] = min(abs(YUa(2,m:n)-y2s)) ;
	m = m + FN(1) - 1 ;
	y1sr = YUa(1,m) ;
	y2sr = YUa(2,m) ;
	u1s = YUa(3,m) ;
	u2s = YUa(4,m) ; 
%
% END
% ~~~
